# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.5

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.5
      env: TOXENV=pylint
    - python: 3.5
      env: TOXENV=mypy


install: pip install -U tox

script: tox -e ${TOXENV}


